Setup
Omwomo/bookstore pull request #1
Opened 2023-09-01 09:59 UTC by Omwomo

- Created React App.
- Set up linters for the project.
- Create two navigation routes
- Create component for individual book states
- Create component to render book lists.
- Create navigation links to the two routes created.

2023-09-01 10:12 UTC, codepantha reviewed
# STATUS: INVALID REVIEW REQUEST 🔴 

## Hi @Omwomo 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that doesn't have a professional README that closely mirrors the recommended [template](https://github.com/microverseinc/readme-template) from Microverse.
Kindly note that you should also rename your readme from `README.old.md` to `README.md` 👍 

<img src="https://media2.giphy.com/media/G4E2L5v6y32jNLcIAM/giphy-downsized-medium.gif"/>

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-09-01 10:47 UTC, HAMMAS-SALEEM reviewed
# Invalid Submission :red_circle:

![invalid-submission](https://user-images.githubusercontent.com/93039359/221218445-05489541-f840-492c-878e-0587cc2b3702.gif)

## Hey @Omwomo :wave:

Good job on implementing some of the requirements but I cannot proceed review of your pull request because there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-01 10:47 UTC, HAMMAS-SALEEM commented on README.md
> +
- [ ] Kindly remove this section description to make your readme descriptive and clean 😊

2023-09-01 10:47 UTC, HAMMAS-SALEEM commented on README.md
> +
- [ ] Kindly remove this section description to make your readme descriptive and clean 😊

2023-09-01 10:47 UTC, HAMMAS-SALEEM commented on README.md
> +
- [ ] Kindly remove this section description to make your readme descriptive and clean 😊

2023-09-01 10:47 UTC, HAMMAS-SALEEM commented on README.md
> +
- [ ] Kindly remove this section description to make your readme descriptive and clean 😊

2023-09-01 10:47 UTC, HAMMAS-SALEEM commented on README.md
> +
- [ ] Kindly remove this section description to make your readme descriptive and clean 😊

2023-09-01 10:47 UTC, HAMMAS-SALEEM commented on README.md
> +
- [ ] Kindly remove this section description to make your readme descriptive and clean 😊

2023-09-01 10:47 UTC, HAMMAS-SALEEM commented on README.md
> +
- [ ] Kindly remove this section description to make your readme descriptive and clean 😊

2023-09-01 14:09 UTC, mikethreels requested changes
Hi Eugene, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- good job creating the components

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-01 14:09 UTC, mikethreels commented on README.md
> -
- [ ] you removed the whole part of the readme file, what the previous CR meant, however, was for you to remove just the lines

2023-09-01 14:09 UTC, mikethreels commented on src/components/Book.js
> +      <Form />
- [ ] if you call the form from the book property the form will be visible the same amount of times as the amount of books in the array, the form however should only be visible once therefore it is better to call it from another component.

2023-09-01 18:48 UTC, Alusp requested changes
Hi @Omwomo, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![close](https://media.giphy.com/media/nJKDTpuxnZE7fb6Z1b/giphy.gif)

 ## Highlights

- [ ] good job creating the components :clap: 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-01 18:48 UTC, Alusp commented on README.md
> +> Project description.
`> Project description.`

- [ ] Good job so far, however, as mentioned by the previous code reviewers, please remove the above line of code because they are only meant to be placeholders.

2023-09-01 18:48 UTC, Alusp commented on README.md
> +> The link to the deployed project.
`> The link to the deployed project.`

- [ ] Good job so far, however, as mentioned by the previous code reviewers, please remove the above line of code because they are only meant to be placeholders.

2023-09-01 18:48 UTC, Alusp commented on README.md
> +- [Live Demo Link](#)
`- [Live Demo Link](#)`

- [ ] Good job so far, however, as mentioned by the previous code reviewers, please remove the above line of code since you do not have a Live demo version yet.

2023-09-01 18:48 UTC, Alusp commented on README.md
> +> Tech stack included in this project.
`> Tech stack included in this project.`

- [ ] Good job so far, however, as mentioned by the previous code reviewers, please remove the above line of code because they are only meant to be placeholders.

2023-09-01 18:48 UTC, Alusp commented on README.md
> +> Description of the project key features.
`> Description of the project key features.`

- [ ] Good job so far, however, as mentioned by the previous code reviewers, please remove the above line of code because they are only meant to be placeholders.

2023-09-01 18:48 UTC, Alusp commented on README.md
> +> Here's is how a developer could make use this project.
`> Here's is how a developer could make use this project.`

- [ ] Good job so far, however, as mentioned by the previous code reviewers, please remove the above line of code because they are only meant to be placeholders.

2023-09-01 18:48 UTC, Alusp commented on README.md
> +> Description of future features that will be added to the project.
`>  Description of future features that will be added to the project.`

- [ ] Good job so far, however, as mentioned by the previous code reviewers, please remove the above line of code because they are only meant to be placeholders.

2023-09-01 18:48 UTC, Alusp commented on README.md
> +> A message for users to support my project.
`>  A message for users to support my project.`

- [ ] Good job so far, however, as mentioned by the previous code reviewers, please remove the above line of code because they are only meant to be placeholders.

2023-09-01 18:48 UTC, Alusp commented on README.md
> +> Credit to people who inspired my codebase.
`> Credit to people who inspired my codebase.`

- [ ] Good job so far, however, as mentioned by the previous code reviewers, please remove the above line of code because they are only meant to be placeholders.

2023-09-01 18:48 UTC, Alusp commented on src/App.js
> +      <Form />
- [ ] Good job in implementing the changes requested by the previous reviewer, however,  if you place the `<Form/>` in `App.js` file, it will show up in the Categories sections, The possible solution would be to place it in `BookList`  Component then it will show only on the Book section. :slightly_smiling_face:

2023-09-02 06:06 UTC, usorfaitheloho approved these changes
Hi @Omwomo  , 
# STATUS: APPROVED! 🥇 💯 

![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-02 06:08 UTC, merged