Connecting to api.
Omwomo/bookstore pull request #5
Opened 2023-09-07 10:47 UTC by Omwomo

- Used axios with createAsyncThunk to make HTTP requests to the backend.
- Fetched your books from the Bookstore API.
- Refactored my add book and remove book features to persist changes in the server.

2023-09-07 11:53 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![Ukhv](https://user-images.githubusercontent.com/93039359/247195854-e274f284-2e3a-423b-8939-7e4efb638ee0.gif)

## Hey @Omwomo :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Gitflow
✔️ Following some requirements
✔️ Great work on implementing the API well 👍

Good job on implementing some of the requirements, There are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-07 11:53 UTC, HAMMAS-SALEEM commented on src/components/BookList.js
>        <ul className="books">
![image](https://github.com/Omwomo/bookstore/assets/93039359/e4f5d832-0a13-4669-b21c-cc7574289c14)

![image](https://github.com/Omwomo/bookstore/assets/93039359/8df3d52e-a399-4714-a32a-8202b76c1906)

- [ ] Great work on implementing the API but your app is not rendering the books from the API :fearful: Kindly make your line 33 such as below to fix the books rendering problem :arrow_down: :blush: The only problem here is the structure of your API :thinking: Kindly map the data according to the API structure :+1:

### API Structure :arrow_down:

![image](https://github.com/Omwomo/bookstore/assets/93039359/f3807deb-b742-45a8-9c66-b8d7c1c6af2d)

2023-09-07 11:53 UTC, HAMMAS-SALEEM commented on src/components/Form.js
> -      id: `item${Math.floor(Math.random() * 1000)}`,
- [ ] Kindly don't remove the id because if there is no id then we are not able to add any book to your API using your form 😨 Kindly put the id back 😊 
- [ ] Kindly fix the issues i have mentioned because remove button is also not working so kindly fix it too to make your app work as expected 👍

2023-09-07 11:53 UTC, HAMMAS-SALEEM commented on README.md
**[OPTIONAL BUT HIGHLY RECOMMENDED]**

- [ ] It would be nice if you make your own logo of your name and put that in the readme file at the top to present yourself as a brand in the job market or tech industry to catch the recruiters' eyes 👍

2023-09-07 11:56 UTC, HAMMAS-SALEEM commented on src/redux/books/bookSlice.js
> +    return response.data;
- [ ] Kindly remove the commented piece of code to make your codebase clean to follow JavaScript best practices 👍

2023-09-07 16:33 UTC, skyv26 requested changes
## Hi @Omwomo, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOTljYjFhMDZmNmM4MTA2ZmNlOGEzY2E1ZjE5OWM3MDc5NzM5MGE0MyZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/2sGZ6lqDkf1HW1q0sk/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
- Professional `README` template ✅ 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-07 16:33 UTC, skyv26 commented on src/components/Form.js
>    );
- [ ] Well done by implementing the changes asked by your previous code reviewer, but as per the instructions of the last reviewer code, you are supposed to improve the functionality by putting back the book IDs while adding the new book. But after adding the ID your application is giving an error while adding the new book. Please make sure that your application should work without any errors.

### Error
![image](https://github.com/Omwomo/bookstore/assets/66476329/ff67db45-ff74-4c41-9fbb-422efbfde175)

2023-09-07 16:33 UTC, skyv26 commented on src/components/BookList.js
> +            onRemove={() => handleRemoveBook(book.item_id)}
- [ ] As I mentioned earlier always double-check your work and make sure that you are fulfilling the requirements of the projects as per instructions. Your previous code reviewer even pointed out the issue related to having the issue of deleting the added book or any specific book. But it seems like you haven't improved your functionality. Kindly fix the issue and try to figure out why book delete button is not working the way it should work.

2023-09-08 08:47 UTC, Abenezer-Tilahun commented on src/components/Form.js
>    );
Fixed.

2023-09-08 08:47 UTC, Abenezer-Tilahun commented on src/components/BookList.js
> +            onRemove={() => handleRemoveBook(book.item_id)}
Fixed.

2023-09-08 08:49 UTC, Abenezer-Tilahun approved these changes
Hi @Omwomo 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Git-Flow.
✔️ Professional README  
✔️ Good Commit Messages
✔️ Good job for Implemented Suggested changes.

## Optional suggestions 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

2023-09-08 09:24 UTC, merged